kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-resources-backup-reader
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-resources-backup
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-resources-backup
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-resources-backup-reader
  apiGroup: rbac.authorization.k8s.io
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-resources-backup